# Раздел 1

In [1]:
import numpy as np
a = np.array([1.2, 2.4, 3.6, 3.5, 6.7, 1.5, 8.4, 3.1, 9.2])

d=a.shape

print(d) 

(9,)


In [11]:
import numpy as np
a = np.array([[2.3, 5.1, 4.7], [3.5, 6.7, 1.5], [8.4, 3.1, 9.2]])
b = np.array([[4.3, 8.1, 6.1], [3.7, 6.2, 1.5], [2.4, 5.7, 4.7]])
s=a**2
print(s)

[[ 5.29 26.01 22.09]
 [12.25 44.89  2.25]
 [70.56  9.61 84.64]]


In [21]:
import numpy as np
a = np.array([[2.3, 5.1, 4.7], [3.5, 6.7, 1.5], [8.4, 3.1, 9.2]])
b = np.array([[4.3, 8.1, 6.1], [3.7, 6.2, 1.5], [2.4, 5.7, 4.7]])
s=b%2
print(s)

[[0.3 0.1 0.1]
 [1.7 0.2 1.5]
 [0.4 1.7 0.7]]


In [31]:
import numpy as np
a = np.array([[2.3, 5.1, 4.7], [3.5, 6.7, 1.5], [8.4, 3.1, 9.2]])
b = np.array([[4.3, 8.1, 6.1], [3.7, 6.2, 1.5], [2.4, 5.7, 4.7]])
s=np.sin(b)
f=np.cos(a)
print(s+f)

[[-1.58244196  1.34786755 -0.19455117]
 [-1.46629283  0.83129375  1.06823219]
 [ 0.15617453 -1.54982069 -1.97476688]]


In [43]:
import numpy as np 
a = np.array([[1.2], [2.4], [3.6], [3.5], [6.7], [1.5], [8.4], [3.1], [9.2]]) 

d=a.shape

print(d)

(9, 1)


In [53]:
import numpy as np 
a = np.array([[1.2, 2.4, 3.6], [3.5, 6.7, 1.5], [8.4, 3.1, 9.2]]) 

d=a.shape
print(a)
print(d)

g=a.max(axis = 1)
j=a.max(axis = 0)
print('макс в каждой строке = ',g)
print('макс в каждой столб = ',j)

k=a.min(axis = 1)
w=a.min(axis = 0)
print('мин в каждой строке = ',k)
print('мин в каждой столб = ',w)

t=a.sum(axis = 1)
u=a.sum(axis = 0)
print('сум в каждой строке = ',t)
print('сум в каждой столб = ',u)


[[1.2 2.4 3.6]
 [3.5 6.7 1.5]
 [8.4 3.1 9.2]]
(3, 3)
макс в каждой строке =  [3.6 6.7 9.2]
макс в каждой столб =  [8.4 6.7 9.2]
мин в каждой строке =  [1.2 1.5 3.1]
мин в каждой столб =  [1.2 2.4 1.5]
сум в каждой строке =  [ 7.2 11.7 20.7]
сум в каждой столб =  [13.1 12.2 14.3]


In [63]:
import numpy as np 
a = np.array([[4, 2], [9, 1]]) 
b = np.array([[5, 3], [2, 5]]) 
f=np.vstack((a, b)) 
print(f)

g=f[:-1,0]
print(g)

y=g.sum() # Нахождение суммы элементов массива
o=g.min() # Нахождения минимума массива 
x=g.max() 
print('сум=',y,'мин=',o,'макс=',x)

d=np.hstack((a, b))
print(d)

h=d[0, :-1]
print(h)

q=h.sum() # Нахождение суммы элементов массива
w=h.min() # Нахождения минимума массива 
r=h.max() 
print('сум=',q,'мин=',w,'макс=',r)


[[4 2]
 [9 1]
 [5 3]
 [2 5]]
[4 9 5]
сум= 18 мин= 4 макс= 9
[[4 2 5 3]
 [9 1 2 5]]
[4 2 5]
сум= 11 мин= 2 макс= 5


In [73]:
import numpy as np 
a=np.array([[5,4],[2,-6]])
b=np.array([14,-2])
d=np.linalg.solve(a, b) 
print(d)


[2. 1.]


In [83]:
import numpy as np 
a=np.array([[2,8],[1,6]])
b=np.array([[3,2,7],[4,1,8],[6,3,7]])
g=np.array([[4,3,2,7],[6,1,1,-2],[7,5,8,1],[9,5,-3,-5]])

d=a.transpose() 
z=b.transpose() 
i=g.transpose() 
print(' транспонированную',d)
print(z)
print(i)

t = np.linalg.inv(a)
y = np.linalg.inv(b)
o= np.linalg.inv(g)
print('обратная',t)
print(y)
print(o)

a1 = np.linalg.det(a)
a2 = np.linalg.det(b)
a3 = np.linalg.det(g)
print('определитель',a1)
print('определитель',a2)
print('определитель', round(a3,2) )

b1=np.linalg.norm(b, ord=1)
print('норма 3 на 3',b1)

b2=np.linalg.norm(g, ord=1)
print('норма 4 на 4',b2)


 транспонированную [[2 1]
 [8 6]]
[[3 4 6]
 [2 1 3]
 [7 8 7]]
[[ 4  6  7  9]
 [ 3  1  5  5]
 [ 2  1  8 -3]
 [ 7 -2  1 -5]]
обратная [[ 1.5  -2.  ]
 [-0.25  0.5 ]]
[[-0.5483871   0.22580645  0.29032258]
 [ 0.64516129 -0.67741935  0.12903226]
 [ 0.19354839  0.09677419 -0.16129032]]
[[ 0.05464191  0.23129973 -0.05251989 -0.0265252 ]
 [-0.00424403 -0.37718833  0.11087533  0.16710875]
 [-0.06153846  0.03076923  0.10769231 -0.07692308]
 [ 0.13103448  0.02068966 -0.04827586 -0.03448276]]
определитель 4.0
определитель 31.0
определитель 1885.0
норма 3 на 3 22.0
норма 4 на 4 26.0


In [93]:
import numpy as np 
import random 
a = np.array([random.randint(0, 100) for i in range(0, 100, 1)]) 

cnt = 0 
for a in a: 
 if a > 50: 
    cnt +=1 
print(cnt) 

a1=np.array([random.randint(0, 100) for i in range(0, 100, 1)]) 
print((a1 > 50).sum()) 

43
52


In [103]:
import numpy as np 
a = np.array([[2.3, 5.1, 4.7],  [3.5, 6.7, 1.5], [8.4, 3.1, 9.2]]) 
b = np.array([[4.3, 8.1, 6.1],  [3.7, 6.2, 1.5],  [2.4, 5.7, 4.7]])
s=a**2
print(s)

[[ 5.29 26.01 22.09]
 [12.25 44.89  2.25]
 [70.56  9.61 84.64]]


In [113]:
import numpy as np 
a = np.array([[2.3, 5.1, 4.7],  [3.5, 6.7, 1.5], [8.4, 3.1, 9.2]]) 
b = np.array([[4.3, 8.1, 6.1],  [3.7, 6.2, 1.5],  [2.4, 5.7, 4.7]])
s=b%2
print(s)

[[0.3 0.1 0.1]
 [1.7 0.2 1.5]
 [0.4 1.7 0.7]]


In [123]:
import numpy as np 
a = np.array([[2.3, 5.1, 4.7],  [3.5, 6.7, 1.5], [8.4, 3.1, 9.2]]) 
b = np.array([[4.3, 8.1, 6.1],  [3.7, 6.2, 1.5],  [2.4, 5.7, 4.7]])
s=np.sin(b)
f=np.cos(a)
print(s+f)

[[-1.58244196  1.34786755 -0.19455117]
 [-1.46629283  0.83129375  1.06823219]
 [ 0.15617453 -1.54982069 -1.97476688]]


# Раздел 2

### Заданеие 2.1

In [124]:

import pandas as pd 
heights = [188, 172, 187, 161, 183, 172, 185, 163, 173, 183, 174, 174, 175,
178, 183, 195, 178, 173, 174, 183, 174, 181, 162, 180, 170, 175, 182, 180, 183,
178, 182, 188, 175, 179, 184, 193, 182, 183, 175, 185, 182, 183, 156, 185, 199] 
weights = [86, 71, 89, 64, 83, 71, 86, 68, 73, 84, 73, 72, 75, 78, 85, 93, 78,
70, 74, 80, 83, 82, 68, 80, 73, 78, 82, 81, 83, 79, 82, 86, 76, 77, 80, 103,
82, 83, 77, 89, 80, 85, 82, 85, 110] 
ages = [58, 61, 54, 54, 58, 57, 63, 54, 37, 51, 34, 26, 50, 48, 45, 52, 56,
46, 54, 28, 52, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 32, 21, 62, 43, 55,
56, 61, 53, 22, 64, 45, 54, 47, 38] 

data = {"heights":heights,"weights":weights,"ages":ages}
df = pd.DataFrame(data)

print(df.head(3)) 
print(df.tail(3)) 

   heights  weights  ages
0      188       86    58
1      172       71    61
2      187       89    54
    heights  weights  ages
42      156       82    54
43      185       85    47
44      199      110    38


### Задание 2.2


In [125]:
import pandas as pd 
heights = [188, 172, 187, 161, 183, 172, 185, 163, 173, 183, 174, 174, 175,
178, 183, 195, 178, 173, 174, 183, 174, 181, 162, 180, 170, 175, 182, 180, 183,
178, 182, 188, 175, 179, 184, 193, 182, 183, 175, 185, 182, 183, 156, 185, 199] 
weights = [86, 71, 89, 64, 83, 71, 86, 68, 73, 84, 73, 72, 75, 78, 85, 93, 78,
70, 74, 80, 83, 82, 68, 80, 73, 78, 82, 81, 83, 79, 82, 86, 76, 77, 80, 103,
82, 83, 77, 89, 80, 85, 82, 85, 110] 
ages = [58, 61, 54, 54, 58, 57, 63, 54, 37, 51, 34, 26, 50, 48, 45, 52, 56,
46, 54, 28, 52, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 32, 21, 62, 43, 55,
56, 61, 53, 22, 64, 45, 54, 47, 38] 

data = {"heights":heights,"weights":weights,"ages":ages}
df = pd.DataFrame(data)

print(df.head(3)) 
print(df.tail(3)) 

#макс значение
maxdf=df.max()
mindf=df.min()
print(maxdf)

#мин значение
mindf=df.min()
mindf=df.min()
print(mindf)

# среднее значение с мин
res_mean = df.mean()
print(res_mean)

#сред значение без мин ages
sum_ag=sum(ages)
print('сумма чисел',sum_ag)
dlina_ag=len(ages)
sred_ag=sum_ag/dlina_ag
print('длина ',dlina_ag)
print('среднее значение без мин ',sred_ag)

#сред значение без мин heights
sum_he=sum(heights)
print('сумма чисел',sum_he)
dlina_he=len(heights)
sred_he=sum_he/dlina_he
print('длина ',dlina_he)
print('среднее значение без мин ',sred_he)

#сред значение без мин weights
sum_we=sum(weights)
print('сумма чисел',sum_we)
dlina_we=len(weights)
sred_we=sum_we/dlina_we
print('длина ',dlina_we)
print('среднее значение без мин ',sred_we)

#Медиана
mediannn=df.median()
print(' медиана',mediannn)

#стандартное отклонение 
stand=df.std()
print(' стандартное откл ',stand)

   heights  weights  ages
0      188       86    58
1      172       71    61
2      187       89    54
    heights  weights  ages
42      156       82    54
43      185       85    47
44      199      110    38
heights    199
weights    110
ages        64
dtype: int64
heights    156
weights     64
ages        21
dtype: int64
heights    178.888889
weights     80.422222
ages        49.133333
dtype: float64
сумма чисел 2211
длина  45
среднее значение без мин  49.13333333333333
сумма чисел 8050
длина  45
среднее значение без мин  178.88888888888889
сумма чисел 3619
длина  45
среднее значение без мин  80.42222222222222
 медиана heights    180.0
weights     80.0
ages        53.0
dtype: float64
 стандартное откл  heights     8.501931
weights     8.438249
ages       10.674098
dtype: float64


### Задание 2.3


In [126]:
import pandas as pd 
heights = [188, 172, 187, 161, 183, 172, 185, 163, 173, 183, 174, 174, 175,
178, 183, 195, 178, 173, 174, 183, 174, 181, 162, 180, 170, 175, 182, 180, 183,
178, 182, 188, 175, 179, 184, 193, 182, 183, 175, 185, 182, 183, 156, 185, 199] 
weights = [86, 71, 89, 64, 83, 71, 86, 68, 73, 84, 73, 72, 75, 78, 85, 93, 78,
70, 74, 80, 83, 82, 68, 80, 73, 78, 82, 81, 83, 79, 82, 86, 76, 77, 80, 103,
82, 83, 77, 89, 80, 85, 82, 85, 110] 
ages = [58, 61, 54, 54, 58, 57, 63, 54, 37, 51, 34, 26, 50, 48, 45, 52, 56,
46, 54, 28, 52, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 32, 21, 62, 43, 55,
56, 61, 53, 22, 64, 45, 54, 47, 38] 

data = {'heights': heights, 'weights': weights, 'ages': ages}

df = pd.DataFrame(data)

stat=df.describe()
print(stat)


          heights     weights       ages
count   45.000000   45.000000  45.000000
mean   178.888889   80.422222  49.133333
std      8.501931    8.438249  10.674098
min    156.000000   64.000000  21.000000
25%    174.000000   75.000000  45.000000
50%    180.000000   80.000000  53.000000
75%    183.000000   84.000000  55.000000
max    199.000000  110.000000  64.000000


# Раздел 3





## Задание 3.1

In [127]:
import pandas as pd 
heights = [188, 172, 187, 161, 183, 172, 185, 163, 173, 183, 174, 174, 175,
178, 183, 195, 178, 173, 174, 183, 174, 181, 162, 180, 170, 175, 182, 180, 183,
178, 182, 188, 175, 179, 184, 193, 182, 183, 175, 185, 182, 183, 156, 185, 199] 
weights = [86, 71, 89, 64, 83, 71, 86, 68, 73, 84, 73, 72, 75, 78, 85, 93, 78,
70, 74, 80, 83, 82, 68, 80, 73, 78, 82, 81, 83, 79, 82, 86, 76, 77, 80, 103,
82, 83, 77, 89, 80, 85, 82, 85, 110] 
ages = [58, 61, 54, 54, 58, 57, 63, 54, 37, 51, 34, 26, 50, 48, 45, 52, 56,
46, 54, 28, 52, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 32, 21, 62, 43, 55,
56, 61, 53, 22, 64, 45, 54, 47, 38] 

data = {'heights': heights, 'weights': weights, 'ages': ages}

df = pd.DataFrame(data)

stat=df.describe()
a=df.loc[:40]
print(a)


    heights  weights  ages
0       188       86    58
1       172       71    61
2       187       89    54
3       161       64    54
4       183       83    58
5       172       71    57
6       185       86    63
7       163       68    54
8       173       73    37
9       183       84    51
10      174       73    34
11      174       72    26
12      175       75    50
13      178       78    48
14      183       85    45
15      195       93    52
16      178       78    56
17      173       70    46
18      174       74    54
19      183       80    28
20      174       83    52
21      181       82    47
22      162       68    55
23      180       80    55
24      170       73    54
25      175       78    42
26      182       82    51
27      180       81    56
28      183       83    55
29      178       79    51
30      182       82    54
31      188       86    32
32      175       76    21
33      179       77    62
34      184       80    43
35      193      103    55
3

## Задание 3.2


In [128]:
import pandas as pd 
heights = [188, 172, 187, 161, 183, 172, 185, 163, 173, 183, 174, 174, 175,
178, 183, 195, 178, 173, 174, 183, 174, 181, 162, 180, 170, 175, 182, 180, 183,
178, 182, 188, 175, 179, 184, 193, 182, 183, 175, 185, 182, 183, 156, 185, 199] 
weights = [86, 71, 89, 64, 83, 71, 86, 68, 73, 84, 73, 72, 75, 78, 85, 93, 78,
70, 74, 80, 83, 82, 68, 80, 73, 78, 82, 81, 83, 79, 82, 86, 76, 77, 80, 103,
82, 83, 77, 89, 80, 85, 82, 85, 110] 
ages = [58, 61, 54, 54, 58, 57, 63, 54, 37, 51, 34, 26, 50, 48, 45, 52, 56,
46, 54, 28, 52, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 32, 21, 62, 43, 55,
56, 61, 53, 22, 64, 45, 54, 47, 38] 

data = {'heights': heights, 'weights': weights, 'ages': ages}

df = pd.DataFrame(data)

a=df.loc[:40]
b=df[(df["heights"]>180)]["heights"]
print(b)
df_n=df[["heights","ages"]][0:20]


0     188
2     187
4     183
6     185
9     183
14    183
15    195
19    183
21    181
26    182
28    183
30    182
31    188
34    184
35    193
36    182
37    183
39    185
40    182
41    183
43    185
44    199
Name: heights, dtype: int64


## Задание 3.3

In [129]:
import pandas as pd 
heights = [188, 172, 187, 161, 183, 172, 185, 163, 173, 183, 174, 174, 175,
178, 183, 195, 178, 173, 174, 183, 174, 181, 162, 180, 170, 175, 182, 180, 183,
178, 182, 188, 175, 179, 184, 193, 182, 183, 175, 185, 182, 183, 156, 185, 199] 
weights = [86, 71, 89, 64, 83, 71, 86, 68, 73, 84, 73, 72, 75, 78, 85, 93, 78,
70, 74, 80, 83, 82, 68, 80, 73, 78, 82, 81, 83, 79, 82, 86, 76, 77, 80, 103,
82, 83, 77, 89, 80, 85, 82, 85, 110] 
ages = [58, 61, 54, 54, 58, 57, 63, 54, 37, 51, 34, 26, 50, 48, 45, 52, 56,
46, 54, 28, 52, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 32, 21, 62, 43, 55,
56, 61, 53, 22, 64, 45, 54, 47, 38] 

data = {'heights': heights, 'weights': weights, 'ages': ages}

df = pd.DataFrame(data)

a=df.loc[:40]
b=df[(df["weights"]<80)]["weights"]
print(b)
df_n=df[["weights","ages"]][0:20]

1     71
3     64
5     71
7     68
8     73
10    73
11    72
12    75
13    78
16    78
17    70
18    74
22    68
24    73
25    78
29    79
32    76
33    77
38    77
Name: weights, dtype: int64


## Задание 3.4.


In [130]:
import pandas as pd 
heights = [188, 172, 187, 161, 183, 172, 185, 163, 173, 183, 174, 174, 175,
178, 183, 195, 178, 173, 174, 183, 174, 181, 162, 180, 170, 175, 182, 180, 183,
178, 182, 188, 175, 179, 184, 193, 182, 183, 175, 185, 182, 183, 156, 185, 199] 
weights = [86, 71, 89, 64, 83, 71, 86, 68, 73, 84, 73, 72, 75, 78, 85, 93, 78,
70, 74, 80, 83, 82, 68, 80, 73, 78, 82, 81, 83, 79, 82, 86, 76, 77, 80, 103,
82, 83, 77, 89, 80, 85, 82, 85, 110] 
ages = [58, 61, 54, 54, 58, 57, 63, 54, 37, 51, 34, 26, 50, 48, 45, 52, 56,
46, 54, 28, 52, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 32, 21, 62, 43, 55,
56, 61, 53, 22, 64, 45, 54, 47, 38] 

data = {'heights': heights, 'weights': weights, 'ages': ages}

df = pd.DataFrame(data)

a=df.loc[:40]
b=df[(df["ages"]<50) & (df["ages"]>30)]["ages"]
print(b)


8     37
10    34
13    48
14    45
17    46
21    47
25    42
31    32
34    43
41    45
43    47
44    38
Name: ages, dtype: int64


## Задание 3.5.

In [131]:
import pandas as pd 
heights = [188, 172, 187, 161, 183, 172, 185, 163, 173, 183, 174, 174, 175,
178, 183, 195, 178, 173, 174, 183, 174, 181, 162, 180, 170, 175, 182, 180, 183,
178, 182, 188, 175, 179, 184, 193, 182, 183, 175, 185, 182, 183, 156, 185, 199] 
weights = [86, 71, 89, 64, 83, 71, 86, 68, 73, 84, 73, 72, 75, 78, 85, 93, 78,
70, 74, 80, 83, 82, 68, 80, 73, 78, 82, 81, 83, 79, 82, 86, 76, 77, 80, 103,
82, 83, 77, 89, 80, 85, 82, 85, 110] 
ages = [58, 61, 54, 54, 58, 57, 63, 54, 37, 51, 34, 26, 50, 48, 45, 52, 56,
46, 54, 28, 52, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 32, 21, 62, 43, 55,
56, 61, 53, 22, 64, 45, 54, 47, 38] 

data = {'heights': heights, 'weights': weights, 'ages': ages}

df = pd.DataFrame(data)

a=df.loc[:40]
b=df[(df["heights"]>170) & (df["weights"]>80)][["heights", "weights"]]
print(b)

    heights  weights
0       188       86
2       187       89
4       183       83
6       185       86
9       183       84
14      183       85
15      195       93
20      174       83
21      181       82
26      182       82
27      180       81
28      183       83
30      182       82
31      188       86
35      193      103
36      182       82
37      183       83
39      185       89
41      183       85
43      185       85
44      199      110


In [132]:
print('мин знач',b['heights'].min(), b['weights'].min())
print('макс знач',b['heights'].max(), b['weights'].max())

# среднее значение с мин
print(' среднее знач ', b['heights'].mean(), b['weights'].mean())

#стандартное отклонение
print(' стандартное откл ',b['heights'].std(), b['weights'].std())

мин знач 174 81
макс знач 199 110
 среднее знач  184.95238095238096 86.76190476190476
 стандартное откл  5.454137791403793 7.251929135786986
